# Generated by Django 4.0.2 on 2022-02-26 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=100)),
                ('sort_field', models.CharField(blank=True, default=None, max_length=50)),
                ('sort_value', models.CharField(blank=True, default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_title', models.CharField(max_length=300)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.answer')),
            ],
        ),
    ]
