# Generated by Django 4.0.2 on 2022-02-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='a_title',
            new_name='answer_title',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='q_title',
            new_name='question_title',
        ),
    ]
