# Generated by Django 4.0.2 on 2022-03-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_alter_client_options_answer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eq_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Eq_Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assistant.eq_category')),
            ],
        ),
        migrations.CreateModel(
            name='Eq_Drilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Equipment', to='assistant.eq_category')),
                ('characteristic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Equipment', to='assistant.eq_characteristics')),
                ('drilling_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Equipment', to='assistant.eq_drilling')),
            ],
        ),
    ]
