# Generated by Django 4.0.2 on 2022-03-02 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_eq_category_eq_characteristics_eq_drilling_equipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eq_category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='eq_characteristics',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='eq_drilling',
            options={'verbose_name': 'Тип бура', 'verbose_name_plural': 'Типы бура'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудования'},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='characteristic',
        ),
        migrations.AddField(
            model_name='eq_characteristics',
            name='equipment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assistant.equipment'),
        ),
    ]
