# Generated by Django 4.0.2 on 2022-03-02 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0009_alter_eq_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eq_characteristics',
            name='equipment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Equipment', to='assistant.equipment'),
        ),
    ]
