# Generated by Django 4.0.2 on 2022-03-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0010_alter_eq_characteristics_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eq_characteristics',
            name='category',
        ),
        migrations.AddField(
            model_name='eq_characteristics',
            name='value',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
