# Generated by Django 4.0.2 on 2022-03-03 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0011_remove_eq_characteristics_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eq_characteristics',
            name='equipment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='assistant.equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='assistant.eq_category'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='drilling_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='assistant.eq_drilling'),
        ),
    ]
