# Generated by Django 4.0.2 on 2022-03-20 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0014_alter_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument', models.CharField(max_length=300)),
                ('objection', models.CharField(max_length=300)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='assistant.question')),
            ],
            options={
                'verbose_name': 'Аргумент на возражение',
                'verbose_name_plural': 'Аргументы на возражения',
            },
        ),
    ]
